### PR TITLE
GeodesicTraining library simplification

### PR DESCRIPTION
**Pull request by dboun**
I put a flat hierarchy to GeodesicTraining. Everything gets put into one Library and the only thing that is needed is for the library to be included in gui's target_link_libraries. And that seems to work, fMainWindow can see everything.

Not 100% sure it works though because I built CaPTk with all the BUILD_[MODULE] options turned off, and some apps (unrelated to GeodesicTraining) compained. Please try to build it yourself, too.

### CODE REVIEW

**Comment by dboun** [comment]
**Note:** I never got Travis to work. But still it might say that checks passed, so ignore that.

**Comment by sarthakpati** [comment]
Understood. I have opened an issue for us to investigate the Travis issues.

**Comment by dboun** [comment]
Apart from travis, does it work?

**Comment by sarthakpati** [comment]
That is what Gray and I will try today and post on the related issue.

**Pull request merged**
